CloudioEnpoint: modify constructor allowing uuid set from .properties
cloudio-project/cloudio-endpoint-java pull request #23
Opened 2020-03-04 14:06 UTC by RandomReaper

```new CloudioEnpoint("application_name")``` will look for ```application_name.properties``` in the usual places, then set the uuid from the ```ch.hevs.cloudio.endpoint.uuid``` property.

Using that constructor, the application does not need to know the uuid before loading the configuration file.

2020-03-04 14:21 UTC, cm0x4D requested changes

2020-03-04 14:21 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> +        private static final String UUID			                = "ch.hevs.cloudio.endpoint.uuid";
`UUID_PROPERTY`

2020-03-04 14:21 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> +     * @param uuid                              Unique ID of the endpoint or a filename if the {filename}.properties file
- Rename Argument to something like `uuidOrApplicationName`
- Update documentation for all constructors

2020-03-04 14:21 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> -            this.uuid = uuid;
Rename the constructor's parameter to something like `uuidOrApplicationName'

2020-03-04 14:24 UTC, cm0x4D commented
This will become really handy when the deployment service of *0.2* is ready where it is possible to download the complete configuration + all required certificates directly from the REST API.

2020-03-04 15:24 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> +        private static final String UUID			                = "ch.hevs.cloudio.endpoint.uuid";
@RandomReaper To be consistent, we should use UUID_PROPERTY for the key like all others

2020-03-04 15:28 UTC, RandomReaper commented
take #3 contains garbage!

2020-03-04 15:30 UTC, cm0x4D commented
> take #3 contains garbage!

I would rather say the start of a good idea ;-)

2020-03-05 10:07 UTC, cm0x4D approved these changes

2020-03-05 10:13 UTC, merged

2020-03-05 10:14 UTC, cm0x4D commented
Thanks @RandomReaper