Feature/token authentication
cloudio-project/cloudio-endpoint-java pull request #57
Opened 2022-09-05 15:34 UTC by MartinMeyer1

2022-09-05 16:44 UTC, cm0x4D requested changes
Ideally the provisioning should provide all settings for the endpoint.

We should have a quick discussion how such a provisioning will take place and then finish to implement server and endpoint side accordingly.

2022-09-05 16:44 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> + *         <b>ch.hevs.cloudio.endpoint.token</b><br>
It is for provisioning endpoints, so I. would prefer the key `ch.hevs.cloudio.endpoint.provisioningToken`

2022-09-05 16:44 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> + *         This property contains a single-use authentication token for the endpoint. This token is used to retrieve
This property contains a single-use authentication token for endpoint provisioning. This token is used to retrieve certificates and settings using the cloud.iO Rest API.

2022-09-05 16:44 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> + *         <b>ch.hevs.cloudio.endpoint.apiUrl</b><br>
`ch.hevs.cloudio.endpoint.provisioningUrl`

2022-09-05 16:44 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> + *          Main URL of the cloud.iO Rest API. This URL is used for the certificate retrieval using authentication
Main URL of the cloud.iO Rest API. This URL is used for the certificate and settings retrieval using one-time provisioning with using a provisioning token.<br>

2022-09-05 16:44 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> + *         <b>ch.hevs.cloudio.endpoint.tokenPropertiesPath</b><br>
`ch.hevs.cloudio.endpoint.provisioningSavePath`

2022-09-05 16:44 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> + *         This property is used to specify a path where the retrieved certificates and .properties file from token
This property is used to specify a path where the retrieved certificates and .properties file from the provisioning process will be saved.<br>

This property is optional and taken into account only if token based provisioning is used.
The default value is <b>~/.config/cloud.io/</b>.

IMHO `~/.config/cloud.io/` is a better default as we are not sure the the endpoint is running as root.

2022-09-05 16:44 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> +        private static final String AUTH_TOKEN = "ch.hevs.cloudio.endpoint.token";
`private` static final String PROVISIONING_TOKEN_PROPERTY     = "ch.hevs.cloudio.endpoint.provisioningToken";`

2022-09-05 16:44 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> +        private static final String AUTH_TOKEN_PROPERTIES_PATH = "ch.hevs.cloudio.endpoint.tokenPropertiesPath";
`private static final String PROVISIONING_SAVE_PATH_PROPERTY = "ch.hevs.cloudio.endpoint.provisioningSavePath";
        `

2022-09-05 16:44 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> +        private static final String TOKEN_PROPERTIES_DEFAULT_PATH = "/etc/cloud.io/";
`private static final String TOKEN_PROPERTIES_DEFAULT_PATH = "~/.config/cloud.io/";`

Default path should work even when not  running  as root.

2022-09-05 16:44 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> +        private static final String API_URL = "ch.hevs.cloudio.endpoint.apiUrl";
`private static final String PROVISIONING_URL_PROPERTY       = "ch.hevs.cloudio.endpoint.provisioningUrl";`

2022-09-05 16:44 UTC, cm0x4D commented on src/main/java/ch/hevs/cloudio/endpoint/CloudioEndpoint.java
> +                        HttpRequest request = HttpRequest.newBuilder()
`HttpRequest request = HttpRequest.newBuilder()
                                .uri(new URI(mainURL + "/api/v1/provision/" + token))
                                .GET()
                                .header("Accept", "application/java-archive")
                                .timeout(Duration.of(10, ChronoUnit.SECONDS))
                                .build();`

New API will use the Accept header  to select the format.

2022-09-06 05:37 UTC, MartinMeyer1 commented
@cm0x4D The provisioning can already contains all the properties if you want to. You can add custom properties when creating a token:
![image](https://user-images.githubusercontent.com/48058365/188555056-33c147f6-3df1-42ef-b42b-e573c3ac78c9.png)

2022-09-06 06:20 UTC, cm0x4D commented
Yes, it is possible.  It is still not very user friendly. Most of the parameters should be automatically filled in by the server itself.  In the mean time we can do everything by hand. As the provisioning is a complete separate process from the normal operation, I propose that we add a main function to the java endpoint lib that does nothing but the provisioning. Then the endpoint can be started with that configuration. What do you think about that, @MartinMeyer1 ?

2022-09-06 06:48 UTC, MartinMeyer1 commented
For now, the server fills "ch.hevs.cloudio.endpoint.ssl.authorityPassword" and "ch.hevs.cloudio.endpoint.ssl.clientPassword". I think we can add "ch.hevs.cloudio.endpoint.uuid" and "ch.hevs.cloudio.endpoint.hostUri" (or maybe not if the server is behind a proxy?) by default. But don't you think that the other properties are more "project specific" and should not be filled automatically by the server?
To be sure to understand, your proposal is to have a provisioning class with its own ".properties" file, that provides the endpoint's ".properties"?
I think that having 2 separate files is cleaner than having 2 ".properties" that are then merged.

2022-09-06 06:52 UTC, cm0x4D commented
It would be good to fill in the defaults for important settings by the server and let the user override them. But you are right, there are not many others.

No it is rather a program that receives the settings and uses only program arguments, no properties files at all. I am working on a proof of concept...

2022-09-07 09:45 UTC, lucblender commented
new pr for token provisioning here #58

2022-09-07 09:45 UTC, closed without merging